CREATE TABLE IF NOT EXISTS `guilds` (
	`name` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`level` INT(11) NULL DEFAULT NULL,
	`players` INT(11) NULL DEFAULT NULL,
	`comment` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


ALTER TABLE `users` ADD COLUMN
(
    `guild` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin'
)